version: "3.8"
services:
  app:
    build: .
    container_name: python_dev
    volumes:
      - .:/app
    command: python app.py
    ports:
      - "8000:8000"  # If you're running a web server
